### ISSUE TITLE
How many queries are allowed?

### ISSUE THREAD

**Issue by DuncanMacLeod-WotU** [cescobarresi/ciscoreputation#6]
Hello! I just discovered your Python Script for querying TALOS reputation. Works great :) ! Do you know how many queries are allowed per minute, day or hour? Is there a limit? Can one get blocked making too many queries?

**Comment by cescobarresi** [comment]
I'm glad you enjoy `ciscoreputation`. I don't know how many queries you can make.
I say you should query **a sane amount of times** per day and there should be no problem.

Given the type of data that you can query there's no point in making thousand of queries in a short amount of time because the result would be always the same.
